"""Guard: docs/reference/operators.md stays in sync with the operator registry.

The reference is generated by ``scripts/gen_operator_docs.py`` from the live
registry. These checks catch the common drift where an operator is added but
the doc isn't regenerated (and the "<N> built-in operators" count goes stale).

They are deliberately environment-independent: they never regenerate the doc
(which would vary with which optional extras are installed), only that every
operator registered *in this environment* is documented, and that the doc's own
stated count matches the number of operator entries it contains.
"""

from __future__ import annotations

import re
from pathlib import Path

import voxkitchen.operators  # noqa: F401  (import populates the registry)
from voxkitchen.operators.registry import get_operator, list_operators

_DOC = Path(__file__).resolve().parents[2] / "docs" / "reference" / "operators.md"


def _doc_text() -> str:
    return _DOC.read_text(encoding="utf-8")


def _builtin_operator_names() -> list[str]:
    """Registered operators that ship inside the voxkitchen package.

    Excludes third-party plugins and test-only sentinel operators (e.g. those
    registered by ``tests/unit/pipeline/test_executor_gpu.py``) — only built-in
    operators belong in ``docs/reference/operators.md``.
    """
    return [
        name
        for name in list_operators()
        if get_operator(name).__module__.startswith("voxkitchen.operators.")
    ]


def test_every_registered_operator_is_documented():
    text = _doc_text()
    missing = [name for name in _builtin_operator_names() if f"### `{name}`" not in text]
    assert not missing, (
        f"operators missing from docs/reference/operators.md: {missing} — "
        "regenerate with `python scripts/gen_operator_docs.py -o docs/reference/operators.md`"
    )


def test_stated_count_matches_entry_count():
    text = _doc_text()
    match = re.search(r"\*\*(\d+) built-in operators\*\*", text)
    assert match, "could not find the '**<N> built-in operators**' line in operators.md"
    stated = int(match.group(1))
    entries = len(re.findall(r"^### `", text, flags=re.MULTILINE))
    assert stated == entries, (
        f"operators.md states {stated} operators but contains {entries} entries — "
        "regenerate with `python scripts/gen_operator_docs.py -o docs/reference/operators.md`"
    )
